name: Process Results

on: push

jobs:
  process-results:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run script
        run: |
          python .github/scripts/process-results.py

      - name: List files in the directory
        run: |
          ls -la resultados/${{ env.DATE }}

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add resultados/${{ env.DATE }}/best_freestylers.txt
          git commit -m "Add best freestylers file"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
